### ISSUE TITLE
Runtime Error On Windows 10

### ISSUE THREAD

**Issue by Enter-tainer** [rqy1458814497/RLJ#2]
When I am trying to run rlj on Windows 10, some errors occured.
Can anyone tell me why?
My python version is 3.6.3 and RLJ version is 1.0.8
```
Margatroid@Margatroid-MiPro MINGW64 ~/Desktop
$ rlj
==============================
正在编译...
编译成功，用时1.142秒
==============================
测试点  状态    内存    时间
==============================
Traceback (most recent call last):
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\_pswindows.py", line 751, in memory_info
    t = self._get_raw_meminfo()
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\_pswindows.py", line 726, in _get_raw_meminfo
    return cext.proc_memory_info(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Margatroid\AppData\Local\Programs\Python\Python36-32\Scripts\rlj-script.py", line 11, in <module>
    load_entry_point('rlj==1.0.8', 'console_scripts', 'rlj')()
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\rlj\main.py", line 171, in main
    printResult(judger.judge(), is_silent)
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\rlj\main.py", line 64, in printResult
    for tesk in result:
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\rlj\judge.py", line 110, in judge
    yield (tesk, self._judge(tesk))
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\rlj\judge.py", line 74, in _judge
    mem_info = ps.memory_info()
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\_common.py", line 337, in wrapper
    return fun(self)
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\__init__.py", line 1049, in memory_info
    return self._proc.memory_info()
  File "c:\users\margatroid\appdata\local\programs\python\python36-32\lib\site-packages\psutil\_pswindows.py", line 640, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=7772)
```

**Comment by rqy2002** [comment]
Emmmm...
Firstly I just want it to run on Linux, and it seems not to support Windows(Sorry that I didn't write this in README).
Secondly, it looks like psutil has an error, not rlj.
Since I don't have an Windows to test, the issue may be open for a long time.

**Comment by rqy2002** [comment]
I don't have a WIN10 machine.
Does it works well now?
If does, I will close the issue.

**Comment by Enter-tainer** [comment]
It **sometimes** works. I mean, it's still buggy. So pls keep this issue open.

**Comment by windows95x** [comment]
Em... I just want to ask you a simple question: 
Why you speak English? (So do I? )
